baseURL: "https://borhez.com"
title: "KBC by Master BoRHeZ"
theme: "PaperMod"
defaultContentLanguage: "en"

params:
  defaultTheme: auto
  homeInfoParams:
    Title: "Welcome to KBC"
    Content: >
      Knowledge is the currency. Knowing is investing.
      Welcome, Master.

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Documents
      url: /docs/
      weight: 2
