baseURL = "https://borhez.com/"
languageCode = "en-us"
title = "KBC by Master BoRHeZ"
theme = "PaperMod"

[params]
author = "Master BoRHeZ"
description = "The official Knowledge-Based Currency (KBC) repository"
defaultTheme = "auto"

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "docs"
name = "Documents"
url = "/docs/"
weight = 2
